<?php

/**
 * @file
 * Module hooks for the Backgrid.js API module.
 */

/**
 * Implements hook_libraries_info().
 */
function backgrid_libraries_info() {
  $libraries['backgrid'] = array(
    'name' => 'Backgrid.js',
    'vendor url' => 'http://backgridjs.com/index.html',
    'download url' => 'https://github.com/wyuenho/backgrid',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/(\d+\.\d+\.\d+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'lib/backgrid.min.js',
      ),
      'css' => array(
        'lib/backgrid.min.css',
      ),
    ),
    'dependencies' => array(
      'underscore (>=1.5)',
      'backbone (>=1.1)',
    ),
  );
  $libraries['backbone-paginator'] = array(
    'name' => 'backbone.paginator',
    'vendor url' => 'https://github.com/backbone-paginator/backbone.paginator',
    'download url' => 'https://github.com/backbone-paginator/backbone.paginator',
    'version arguments' => array(
      'file' => 'lib/backbone.paginator.min.js',
      'pattern' => '/backbone\.paginator (\d+\.\d+\.\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'lib/backbone.paginator.min.js',
      ),
    ),
    'dependencies' => array(
      'backgrid',
    ),
  );
  $libraries['backgrid-paginator'] = array(
    'name' => 'Backgrid.js Paginator',
    'vendor url' => 'https://github.com/wyuenho/backgrid-paginator',
    'download url' => 'https://github.com/wyuenho/backgrid-paginator',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/(\d+\.\d+\.\d+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        // Can't use minified; see https://github.com/wyuenho/backgrid-paginator/issues/24
        'backgrid-paginator.js',
      ),
      'css' => array(
        'backgrid-paginator.min.css',
      ),
    ),
    'dependencies' => array(
      'backgrid',
      'backbone-paginator',
    ),
  );
  $libraries['backgrid-select-all'] = array(
    'name' => 'Backgrid.js SelectAll',
    'vendor url' => 'http://backgridjs.com/ref/extensions/select-all.html',
    'download url' => 'https://github.com/wyuenho/backgrid-select-all',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/(\d+\.\d+\.\d+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'backgrid-select-all.min.js',
      ),
      'css' => array(
        'backgrid-select-all.min.css',
      ),
    ),
    'dependencies' => array(
      'backgrid',
    ),
  );
  $libraries['backgrid-filter'] = array(
    'name' => 'Backgrid.js Filter',
    'vendor url' => 'https://github.com/wyuenho/backgrid-filter',
    'download url' => 'https://github.com/wyuenho/backgrid-filter',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/(\d+\.\d+\.\d+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'backgrid-filter.min.js',
      ),
      'css' => array(
        'backgrid-filter.min.css',
      ),
    ),
  );
  $libraries['underscore'] = array(
    'name' => 'Underscore',
    'vendor url' => 'http://underscorejs.org/',
    'download url' => 'https://github.com/jashkenas/underscore/archive/1.5.2.zip',
    'library path' => 'sites/all/libraries/underscore',
    'version arguments' => array(
      'file' => 'underscore.js',
      'pattern' => '#VERSION *\W *[\'\"]{1}(.*?)[\'\"]{1}#',
      'lines' => 100,
    ),
    'files' => array(
      'js' => array(
        'underscore-min.js',
      ),
    ),
  );
  $libraries['backbone'] = array(
    'name' => 'Backbone',
    'vendor url' => 'http://documentcloud.github.io/backbone/',
    'download url' => 'https://github.com/jashkenas/backbone/archive/1.1.0.zip',
    'library path' => 'sites/all/libraries/backbone',
    'version arguments' => array(
      'file' => 'backbone.js',
      'pattern' => '#VERSION *\W *[\'\"]{1}(.*?)[\'\"]{1}#',
      'lines' => 50,
    ),
    'files' => array(
      'js' => array(
        'backbone-min.js',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function backgrid_theme() {
  return array(
    'backgrid_table' => array(
      'variables' => array(
        'table_id' => NULL,
        'columns' => NULL,
        'data_url' => NULL,
      ),
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Loads scripts to initialize backgrid library.
 */
function backgrid_js_load($table_id, $columns, $data_url) {
  libraries_load('backgrid');
  // Add init script.
  drupal_add_js(drupal_get_path('module', 'backgrid') .'/init-backgrid.js', array('scope' => 'footer'));
  // Add settings.
  drupal_add_js(array('backgrid' => array(
    'basePath' => drupal_get_path('module', 'backgrid'),
    'tables' => array(
      $table_id => array(
        'tableId' => $table_id,
        'columns' => $columns,
        'dataUrl' => $data_url,
      ),
    ),
  )), 'setting');
}

/**
 * Implements hook_libraries_info_alter().
 */
function backgrid_libraries_info_alter(&$libraries) {
  // Added js files for backbone or underscore in case they don't exist.
  if (!empty($libraries['backbone']) && empty($libraries['backbone']['files'])) {
    $libraries['backbone']['files'] = array('js' => array('backbone-min.js'));
  }
  if (!empty($libraries['underscore']) && empty($libraries['underscore']['files'])) {
    $libraries['underscore']['files'] = array('js' => array('underscore-min.js'));
  }
}
